### ISSUE TITLE
more Github Actions

### ISSUE THREAD

**Issue by IdiosApps** [espanso/hub-frontend#23]
There's a few Github Actions I can easily help with, if you're interested!
1. Regular dependabot NPM package updates
2. Automerge dependabot package updates
3. Run tests on PR

I find these very helpful. It wouldn't take me long to add any of them :)

**Comment by IdiosApps** [comment]
Run tests on PR [PR](https://github.com/espanso/hub-frontend/pull/24)

That makes sense RE dependabot :)

I will save some snippets here for a later date. Feel free to close the ticket if you don't want it to hang around 👍 

`.github/dependabot.yml`
```
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
```

`/.github/workflows/auto-merge.yml`
```
name: auto-merge

on:
  pull_request:
    branches:
      - main

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
